---
title: "DDA"
output:
  html_document: default
  pdf_document: default
date: "2023-02-22"
---

# 1. Data description and research question

Here we should state first what is credit scores, highlight their importance and then formulate the research question.

Then, the data should be presented, with a table including each ariable and a brief explanation of each (metadata in other words).

# 2. Data preparation and cleaning 

The following points will be checked to assess the data quality:

- What type of data are we working with? Are data types correct? Do the values make sense?

- Are there erratic values? Are there more categories than expected for categorical variables?

- Are there any missing values? How am I going to deal with them? (Ignore, substitute by median, delete row... and why)

Here we can use str() or summary() to provide a bief description of each variable. We can (if necessary) change variable names to make it easier/more understandable. Also, data types can be changed if needed (for example "character" to "factor"). The validate function is a fancy way of checking this stuff and probably will give higher grades (as we're using additional libraries).

# 3. EDA

For a complete EDA, the following steps will be followed:

- How is each variable distributed? We need graphical visualization. For this, the distribution of the continuous numerical variables will be represented as histograms, while the categorical variables will be portrayed as frequency count barplots. Check for correlation (numerically).

- Is there correlation among variables? To address this, firstly, the dependent variable  will be studied against the other continuous numerical variables. Posteriorly, the relation of the dependent variable with the categorical variables will be portrayed with boxplots, as they are an easy way to visually compare the differences between levels regarding means and IQRs. Check for correlation (numerically).
